---
run:
  timeout: 5m

linters:
  disable-all: true
  presets:
    - bugs
    - unused

  enable:
    - containedctx
    - cyclop
    - dogsled
    - dupl
    - dupword
    - funlen
    - gocognit
    - godot
    - gofmt
    - goimports
    - gosimple
    - goprintffuncname
    - grouper
    - importas
    - interfacebloat
    - lll
    - misspell
    - nilnil
    - nolintlint
    - nosprintfhostport
    - prealloc
    - predeclared
    - promlinter
    - reassign
    - tenv
    - testpackage
    - unconvert
    - usestdlibvars
    - wastedassign

linter-settigns:
  staticcheck:
    checks: ["all"]
