version: "2"
linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - dogsled
    - dupl
    - dupword
    - durationcheck
    - errchkjson
    - errorlint
    - exhaustive
    - funlen
    - gocheckcompilerdirectives
    - gochecksumtype
    - gocognit
    - godot
    - goprintffuncname
    - gosec
    - gosmopolitan
    - grouper
    - importas
    - interfacebloat
    - lll
    - loggercheck
    - makezero
    - misspell
    - nilerr
    - nilnesserr
    - nilnil
    - noctx
    - nolintlint
    - nosprintfhostport
    - prealloc
    - predeclared
    - promlinter
    - protogetter
    - reassign
    - recvcheck
    - rowserrcheck
    - spancheck
    - sqlclosecheck
    - testifylint
    - testpackage
    - unconvert
    - unparam
    - usestdlibvars
    - wastedassign
    - zerologlint
  disable:
    - musttag
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling

formatters:
  enable:
    - gofmt
    - goimports
