---
language: go

before_install:
  - sudo apt update
  - sudo apt install -y libc6-dev libglu1-mesa-dev libgl1-mesa-dev libxcursor-dev libxi-dev libxinerama-dev libxrandr-dev libxxf86vm-dev libasound2-dev pkg-config
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sudo sh -s -- -b /usr/local/bin v1.32.2

git:
  submodules: false

go:
  - 1.15.x

script: >-
  make &&
  make lint &&
  make test
